;; for non-allegro CL systems.
#+Allegro (excl::set-case-mode :case-sensitive-lower)
(load "mma")
(use-package :mma)
(load "uconsalt")
(load "parser")
(load "stack1")
(load "disp1")
(load "eval")
(load "poly")
(load "rat1")
(load "simp1")
(load "pf")
(load "match")
(load "diffrat")
